SET DATABASE EVENT LOG SQL LEVEL 3;

CREATE TABLE users
(
id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
username VARCHAR(120) NOT NULL
);

insert into users(username) values('slawek');
insert into users(username) values('kamil');
